apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend-backend
  template:
    metadata:
      labels:
        app: frontend-backend
    spec:
      containers:
      - name: frontend
        image: psiria/frontend
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env: 
        - name: BASE_URL
          value: http://localhost:9000
      - name: backend
        image: psiria/backend
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@postgres:5432/news
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-backend
  namespace: default
spec:
  selector:
    app: frontend-backend
  ports:
    - name: frontend
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 9000
      targetPort: 9000