apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: first
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://127.0.0.1:60592
    prod:
      defaultNamespace: prod
      server: https://127.0.0.1:60592
    stage:
      defaultNamespace: stage
      server: https://127.0.0.1:60592
  vars: {}
