apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: first
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://127.0.0.1:11949
    prod:
      defaultNamespace: prod
      server: https://127.0.0.1:11949
      includes:
        - endpoint
    stage:
      defaultNamespace: stage
      server: https://127.0.0.1:11949
  vars: {}
  excludes:
    - endpoint
