version: "3.9"

services:
  frontend:
    build: ./frontend
    image: psiria/frontend:latest
    ports:
      - 8000:80

  backend:
    build: ./backend
    image: psiria/backend:latest
    links:
      - db
    ports:
      - 9000:9000

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: news
