all:
  hosts:
    node1:
      ansible_host: 10.0.0.20
      ip: 10.0.0.20
      access_ip: 10.0.0.20
      ansible_user: yc-user
    node2:
      ansible_host: 10.0.0.12
      ip: 10.0.0.12
      access_ip: 10.0.0.12
      ansible_user: yc-user
    node3:
      ansible_host: 10.0.0.29
      ip: 10.0.0.29
      access_ip: 10.0.0.29
      ansible_user: yc-user
    node4:
      ansible_host: 10.0.0.28
      ip: 10.0.0.28
      access_ip: 10.0.0.28
      ansible_user: yc-user
    node5:
      ansible_host: 10.0.0.5
      ip: 10.0.0.5
      access_ip: 10.0.0.5
      ansible_user: yc-user
    cp1:
      ansible_host: 10.0.0.10
      ip: 10.0.0.10
      access_ip: 10.0.0.10
      ansible_user: yc-user
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
