apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: backend-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: backend-{{ .Release.Name }}
    spec:
      containers:
      - name: backend-{{ .Release.Name }}
        image: {{ .Values.backend.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: pv
          mountPath: {{ .Values.volumeMounts.mountPath }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: DATABASE_URL
          value: postgres://{{ .Values.postgres.dbuser}}:{{ .Values.postgres.dbpassword }}@db-{{ .Release.Name }}:{{ .Values.postgres.port }}/{{ .Values.postgres.dbname }}
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.claimName }}-{{ .Release.Name }}