---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db-{{ .Release.Name }}
  name: db-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:  
  selector:
    matchLabels:
      app: db-{{ .Release.Name }}
  serviceName: db-{{ .Release.Name }}
  replicas: {{ .Values.postgres.replicas }}
  template:
    metadata:
      labels:
        app: db-{{ .Release.Name }}
    spec:
      containers:
        - name: db-{{ .Release.Name }}
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.dbuser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.dbpassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbname }}