apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: frontend-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: frontend-{{ .Release.Name }}
    spec:
      containers:
      - name: frontend-{{ .Release.Name }}
        image: {{ .Values.frontend.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: pv
          mountPath: {{ .Values.volumeMounts.mountPath }}
        ports:
        - containerPort: {{ .Values.frontend.port }}
        env:
        - name: BASE_URL
          value: {{ .Values.frontend.BASE_URL }}:{{.Values.backend.port }}
      volumes:
        - name: pv
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.claimName }}-{{ .Release.Name }}