---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Release.Name }}
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.pvc.storage | default "2Gi" }}
  hostPath:
    path: /data/pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.claimName }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "2Gi" }}
